# Generated by Django 5.1 on 2025-04-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_counties'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counties',
            options={'verbose_name_plural': 'Counties'},
        ),
        migrations.RemoveField(
            model_name='counties',
            name='id',
        ),
        migrations.AlterField(
            model_name='counties',
            name='county',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
